// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Translations.Core.Data;

#nullable disable

namespace Translations.Core.Data.Migrations
{
    [DbContext(typeof(TranslationContext))]
    [Migration("20231122214458_AddedIndexToNormalizedTextColumn")]
    partial class AddedIndexToNormalizedTextColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Translations.Core.Entities.Engine", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Engine", "Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enabled = true,
                            Name = "Google Cloud Translate"
                        },
                        new
                        {
                            Id = 2,
                            Enabled = true,
                            Name = "Azure Translator by Microsoft"
                        },
                        new
                        {
                            Id = 3,
                            Enabled = false,
                            Name = "Amazon Translate"
                        },
                        new
                        {
                            Id = 4,
                            Enabled = false,
                            Name = "DeepL"
                        });
                });

            modelBuilder.Entity("Translations.Core.Entities.EngineLanguage", b =>
                {
                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("LanguageId", "EngineId");

                    b.HasIndex("EngineId");

                    b.ToTable("EngineLanguage", "Translations");

                    b.HasData(
                        new
                        {
                            LanguageId = "en",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "es",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fr",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "de",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "zh-CN",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "zh-TW",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ja",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ko",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ru",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ar",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hi",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pt",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "it",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "nl",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sv",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "no",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "da",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fi",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "el",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tr",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "iw",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "th",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "vi",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pl",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "cs",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hu",
                            EngineId = 1,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "af",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sq",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "am",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ar",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hy",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "az",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bn",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bs",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bg",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ca",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "zh-CN",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "zh-TW",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hr",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "cs",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "da",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "nl",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "en",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "et",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fa",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tl",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fi",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fr",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fr-CA",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ka",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "de",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "el",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "gu",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ht",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ha",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "iw",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hi",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hu",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "is",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "id",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ir",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "it",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ja",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "kn",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "kk",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ko",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "lv",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "lt",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mk",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ms",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ml",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mt",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mr",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mn-Cyrl",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "no",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ps",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pl",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pt",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pt-PT",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pa",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ro",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ru",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "si",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sk",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sl",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "so",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "es",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sw",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sv",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ta",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "te",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "th",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tr",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "uk",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ur",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "uz",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "vi",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "cy",
                            EngineId = 3,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "af",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sq",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "am",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ar",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hy",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "as",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "az",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bn",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ba",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "eu",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bho",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "brx",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bs",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bg",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ca",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sn",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hr",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "cs",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "da",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "prs",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "dv",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "doi",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "nl",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "en",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "et",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fo",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fj",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fil",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fi",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fr",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fr-ca",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "gl",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ka",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "de",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "el",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "gu",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ht",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ha",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "iw",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hi",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mww",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hu",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "is",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ig",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "id",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ikt",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "iu",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ir",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "it",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ja",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "kn",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ks",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "kk",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "km",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "rw",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "gom",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ko",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ku",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "kmr",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ky",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "lo",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "lv",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "lt",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ln",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "dsb",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "lug",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mk",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mai",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mg",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ms",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ml",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mt",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mi",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "mr",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "my",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ne",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "no",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "nya",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "or",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ps",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "fa",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pl",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pt",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pt-pt",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "pa",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "otq",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ro",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "run",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ru",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sm",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "st",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "nso",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tn",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sd",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "si",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sk",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sl",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "so",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "es",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sw",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "sv",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ty",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ta",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tt",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "te",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "th",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "bo",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ti",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "to",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tr",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "tk",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "uk",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "hsb",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ur",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "ug",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "uz",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "vi",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "cy",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "yo",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "yua",
                            EngineId = 2,
                            Weight = 0
                        },
                        new
                        {
                            LanguageId = "zu",
                            EngineId = 2,
                            Weight = 0
                        });
                });

            modelBuilder.Entity("Translations.Core.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language", "Translations");

                    b.HasData(
                        new
                        {
                            Id = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = "zh-CN",
                            Name = "Chinese (Simplified)"
                        },
                        new
                        {
                            Id = "zh-TW",
                            Name = "Chinese (Traditional)"
                        },
                        new
                        {
                            Id = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = "ko",
                            Name = "Korean"
                        },
                        new
                        {
                            Id = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = "hi",
                            Name = "Hindi"
                        },
                        new
                        {
                            Id = "pt",
                            Name = "Portugese (Brazil)"
                        },
                        new
                        {
                            Id = "pt-pt",
                            Name = "Portugese (Portugal)"
                        },
                        new
                        {
                            Id = "it",
                            Name = "Italian"
                        },
                        new
                        {
                            Id = "nl",
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = "sv",
                            Name = "Swedish"
                        },
                        new
                        {
                            Id = "no",
                            Name = "Norwegian"
                        },
                        new
                        {
                            Id = "da",
                            Name = "Danish"
                        },
                        new
                        {
                            Id = "fi",
                            Name = "Finnish"
                        },
                        new
                        {
                            Id = "el",
                            Name = "Greek"
                        },
                        new
                        {
                            Id = "tr",
                            Name = "Turkish"
                        },
                        new
                        {
                            Id = "iw",
                            Name = "Hebrew"
                        },
                        new
                        {
                            Id = "th",
                            Name = "Thai"
                        },
                        new
                        {
                            Id = "vi",
                            Name = "Vietnamese"
                        },
                        new
                        {
                            Id = "pl",
                            Name = "Polish"
                        },
                        new
                        {
                            Id = "cs",
                            Name = "Czech"
                        },
                        new
                        {
                            Id = "hu",
                            Name = "Hungarian"
                        },
                        new
                        {
                            Id = "af",
                            Name = "Afrikaans"
                        },
                        new
                        {
                            Id = "sq",
                            Name = "Albanian"
                        },
                        new
                        {
                            Id = "am",
                            Name = "Amharic"
                        },
                        new
                        {
                            Id = "hy",
                            Name = "Armenian"
                        },
                        new
                        {
                            Id = "as",
                            Name = "Assamese"
                        },
                        new
                        {
                            Id = "az",
                            Name = "Azerbaijani (Latin)"
                        },
                        new
                        {
                            Id = "bn",
                            Name = "Bangla"
                        },
                        new
                        {
                            Id = "ba",
                            Name = "Bashkir"
                        },
                        new
                        {
                            Id = "eu",
                            Name = "Basque"
                        },
                        new
                        {
                            Id = "bho",
                            Name = "Bhojpuri"
                        },
                        new
                        {
                            Id = "brx",
                            Name = "Bodo"
                        },
                        new
                        {
                            Id = "bs",
                            Name = "Bosnian (Latin)"
                        },
                        new
                        {
                            Id = "bg",
                            Name = "Bulgarian"
                        },
                        new
                        {
                            Id = "ca",
                            Name = "Catalan"
                        },
                        new
                        {
                            Id = "hr",
                            Name = "Croatian"
                        },
                        new
                        {
                            Id = "prs",
                            Name = "Dari"
                        },
                        new
                        {
                            Id = "dv",
                            Name = "Divehi"
                        },
                        new
                        {
                            Id = "doi",
                            Name = "Dogri"
                        },
                        new
                        {
                            Id = "et",
                            Name = "Estonian"
                        },
                        new
                        {
                            Id = "fo",
                            Name = "Faroese"
                        },
                        new
                        {
                            Id = "fj",
                            Name = "Fijian"
                        },
                        new
                        {
                            Id = "fil",
                            Name = "Filipino"
                        },
                        new
                        {
                            Id = "tl",
                            Name = "Filipino (Tagalog)"
                        },
                        new
                        {
                            Id = "fr-ca",
                            Name = "French (Canada)"
                        },
                        new
                        {
                            Id = "gl",
                            Name = "Galician"
                        },
                        new
                        {
                            Id = "ka",
                            Name = "Georgian"
                        },
                        new
                        {
                            Id = "gu",
                            Name = "Gujarati"
                        },
                        new
                        {
                            Id = "ht",
                            Name = "Haitian Creole"
                        },
                        new
                        {
                            Id = "ha",
                            Name = "Hausa"
                        },
                        new
                        {
                            Id = "mww",
                            Name = "Hmong Daw (Latin)"
                        },
                        new
                        {
                            Id = "is",
                            Name = "Icelandic"
                        },
                        new
                        {
                            Id = "ig",
                            Name = "Igbo"
                        },
                        new
                        {
                            Id = "id",
                            Name = "Indonesian"
                        },
                        new
                        {
                            Id = "ikt",
                            Name = "Inuinnaqtun"
                        },
                        new
                        {
                            Id = "iu",
                            Name = "Inuktitut"
                        },
                        new
                        {
                            Id = "itu-Latin",
                            Name = "Inuktitut (Latin)"
                        },
                        new
                        {
                            Id = "ir",
                            Name = "Irish"
                        },
                        new
                        {
                            Id = "kn",
                            Name = "Kannada"
                        },
                        new
                        {
                            Id = "ks",
                            Name = "Kashmiri"
                        },
                        new
                        {
                            Id = "kk",
                            Name = "Kazahk"
                        },
                        new
                        {
                            Id = "km",
                            Name = "Kymer"
                        },
                        new
                        {
                            Id = "rw",
                            Name = "Kiyarwanda"
                        },
                        new
                        {
                            Id = "tlh-Latn",
                            Name = "Klingon"
                        },
                        new
                        {
                            Id = "gom",
                            Name = "Konkani"
                        },
                        new
                        {
                            Id = "ku",
                            Name = "Kurdish (Central)"
                        },
                        new
                        {
                            Id = "kmr",
                            Name = "Kurdish (Northern)"
                        },
                        new
                        {
                            Id = "ky",
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            Id = "lo",
                            Name = "Lao"
                        },
                        new
                        {
                            Id = "lv",
                            Name = "Latvian"
                        },
                        new
                        {
                            Id = "lt",
                            Name = "Lithuanian"
                        },
                        new
                        {
                            Id = "ln",
                            Name = "Lingala"
                        },
                        new
                        {
                            Id = "dsb",
                            Name = "Lower Sorbian"
                        },
                        new
                        {
                            Id = "lug",
                            Name = "Liganda"
                        },
                        new
                        {
                            Id = "mk",
                            Name = "Macedonian"
                        },
                        new
                        {
                            Id = "mai",
                            Name = "Maithili"
                        },
                        new
                        {
                            Id = "mg",
                            Name = "Malagasy"
                        },
                        new
                        {
                            Id = "ms",
                            Name = "Malay (Latin)"
                        },
                        new
                        {
                            Id = "ml",
                            Name = "Malayalam"
                        },
                        new
                        {
                            Id = "mt",
                            Name = "Maltese"
                        },
                        new
                        {
                            Id = "mi",
                            Name = "Maori"
                        },
                        new
                        {
                            Id = "mr",
                            Name = "Marathi"
                        },
                        new
                        {
                            Id = "mn-Cyrl",
                            Name = "Mongolian (Cyrillic)"
                        },
                        new
                        {
                            Id = "mn-Mong",
                            Name = "Mongilian (Traditional)"
                        },
                        new
                        {
                            Id = "my",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = "ne",
                            Name = "Nepali"
                        },
                        new
                        {
                            Id = "nya",
                            Name = "Nyanja"
                        },
                        new
                        {
                            Id = "or",
                            Name = "Odia"
                        },
                        new
                        {
                            Id = "ps",
                            Name = "Pashto"
                        },
                        new
                        {
                            Id = "fa",
                            Name = "Persian"
                        },
                        new
                        {
                            Id = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            Id = "otq",
                            Name = "Queretaro"
                        },
                        new
                        {
                            Id = "ro",
                            Name = "Romanian"
                        },
                        new
                        {
                            Id = "run",
                            Name = "Rundi"
                        },
                        new
                        {
                            Id = "sm",
                            Name = "Samoan (Latin)"
                        },
                        new
                        {
                            Id = "sr-Cyrl",
                            Name = "Serbian (Cyrillic)"
                        },
                        new
                        {
                            Id = "sr-Latn",
                            Name = "Serbian (Latin)"
                        },
                        new
                        {
                            Id = "st",
                            Name = "Sesotho"
                        },
                        new
                        {
                            Id = "nso",
                            Name = "Sesotho sa Leboa"
                        },
                        new
                        {
                            Id = "tn",
                            Name = "Setswana"
                        },
                        new
                        {
                            Id = "sd",
                            Name = "Sindhi"
                        },
                        new
                        {
                            Id = "si",
                            Name = "Sinhala"
                        },
                        new
                        {
                            Id = "sk",
                            Name = "Slovak"
                        },
                        new
                        {
                            Id = "sl",
                            Name = "Slovenian"
                        },
                        new
                        {
                            Id = "so",
                            Name = "Somali (Arabic)"
                        },
                        new
                        {
                            Id = "sw",
                            Name = "Swahili (Latin)"
                        },
                        new
                        {
                            Id = "ty",
                            Name = "Tahitian"
                        },
                        new
                        {
                            Id = "ta",
                            Name = "Tamil"
                        },
                        new
                        {
                            Id = "tt",
                            Name = "Tatar (Latin)"
                        },
                        new
                        {
                            Id = "te",
                            Name = "Telugu"
                        },
                        new
                        {
                            Id = "bo",
                            Name = "Tibetan"
                        },
                        new
                        {
                            Id = "ti",
                            Name = "Tigrinya"
                        },
                        new
                        {
                            Id = "to",
                            Name = "Tongan"
                        },
                        new
                        {
                            Id = "tk",
                            Name = "Tirkmen (Latin)"
                        },
                        new
                        {
                            Id = "uk",
                            Name = "Ukranian"
                        },
                        new
                        {
                            Id = "hsb",
                            Name = "Upper Sorbian"
                        },
                        new
                        {
                            Id = "ur",
                            Name = "Urdu"
                        },
                        new
                        {
                            Id = "ug",
                            Name = "Uyghur (Arabic)"
                        },
                        new
                        {
                            Id = "uz",
                            Name = "Uzbek (Latin)"
                        },
                        new
                        {
                            Id = "cy",
                            Name = "Welsh"
                        },
                        new
                        {
                            Id = "xh",
                            Name = "Zhosa"
                        },
                        new
                        {
                            Id = "yo",
                            Name = "Yoruba"
                        },
                        new
                        {
                            Id = "yua",
                            Name = "Yucatec Maya"
                        },
                        new
                        {
                            Id = "zu",
                            Name = "Zulu"
                        },
                        new
                        {
                            Id = "es-MX",
                            Name = "Spanish (Mexico)"
                        },
                        new
                        {
                            Id = "sn",
                            Name = "ChiShona"
                        });
                });

            modelBuilder.Entity("Translations.Core.Entities.MachineTranslation", b =>
                {
                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PhraseId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TranslationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("EngineId", "LanguageId", "PhraseId");

                    b.HasIndex("PhraseId");

                    b.HasIndex("LanguageId", "EngineId");

                    b.ToTable("MachineTranslation", "Translations");
                });

            modelBuilder.Entity("Translations.Core.Entities.Phrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedText")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedText")
                        .IsUnique()
                        .HasFilter("[NormalizedText] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("NormalizedText"), false);

                    b.ToTable("Phrase", "Translations");
                });

            modelBuilder.Entity("Translations.Core.Entities.EngineLanguage", b =>
                {
                    b.HasOne("Translations.Core.Entities.Engine", "Engine")
                        .WithMany("Languages")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Translations.Core.Entities.Language", "Language")
                        .WithMany("Engines")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Translations.Core.Entities.MachineTranslation", b =>
                {
                    b.HasOne("Translations.Core.Entities.Engine", "Engine")
                        .WithMany("MachineTranslations")
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Translations.Core.Entities.Phrase", "Phrase")
                        .WithMany("MachineTranslations")
                        .HasForeignKey("PhraseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Translations.Core.Entities.EngineLanguage", "Language")
                        .WithMany("MachineTranslations")
                        .HasForeignKey("LanguageId", "EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Engine");

                    b.Navigation("Language");

                    b.Navigation("Phrase");
                });

            modelBuilder.Entity("Translations.Core.Entities.Engine", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("MachineTranslations");
                });

            modelBuilder.Entity("Translations.Core.Entities.EngineLanguage", b =>
                {
                    b.Navigation("MachineTranslations");
                });

            modelBuilder.Entity("Translations.Core.Entities.Language", b =>
                {
                    b.Navigation("Engines");
                });

            modelBuilder.Entity("Translations.Core.Entities.Phrase", b =>
                {
                    b.Navigation("MachineTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
